### PR TITLE
Update version to 0.0.11 in package.json

### PR DESCRIPTION
**Pull request by ssreekanth**

### CODE REVIEW

**Comment by ragingwind** [comment]
Sorry it's not working. I will publish it as soon as possible when I come back.

**Comment by ssreekanth** [comment]
What didn't work?

**Comment by ragingwind** [comment]
To publish new version. I will publish a new version after tagging through npm command

**Comment by ragingwind** [comment]
released https://github.com/ragingwind/gulp-chrome-manifest/releases/tag/v0.0.11

**Pull request closed without merging**
