### PR TITLE
Add excluding background

### PR DESCRIPTION
**Pull request by oldergod**
Basically just added a condition that would skip the background process if it is included in the `exclude` opts as a string.

Not sure about `manifest.app` though.

### CODE REVIEW

**Comment by oldergod** [comment]
Thanks, fixed it.

btw, there is a lot of tab in the code I was about to replace by spaces but then I thought I would do it in an other PR. Is 2 spaces good for you ?

**Comment by ragingwind** [comment]
@oldergod Thanks. Indent has some of problems. I will fix it.

**Comment by oldergod** [comment]
ok thanks!

**Comment by oldergod** [comment]
fix #7

**Pull request merged**
