### PR TITLE
Stream out packaged resources

### LINKED ISSUE #10: Stream out "web_accessible_resources"
The plug-in should consider [packaged resources](https://developer.chrome.com/extensions/manifest/web_accessible_resources) (that aren't background/content scripts) when processing the manifest.

### PR DESCRIPTION
**Pull request by ramijarrar**
Resolves #10

### CODE REVIEW

**Comment by ragingwind** [comment]
No description about PR, no test, simple concatenation without considering multiple files

**Comment by ramijarrar** [comment]
I took a similar approach to "content_scripts", not sure what you mean about multiple files as the "web_accessible_resources" key is a simple array. As far as description is concerned: I added some more information to #10 but it's a fairly straight-forward change.

I couldn't find any test coverage for the content scripts behaviour so it wasn't entirely clear if that was being maintained (there isn't a contribution guide or anything). In any case, this is a relatively minor addition so if it just simpler for you to implement yourself then that might be the easiest option.

**Comment by ragingwind** [comment]
I didn't get it why this PR is needed. I still wonder why files in `web_accessible_resource` should be streamed out through gulp plugin because this plugin manage those of files related to application code not `the paths of packaged resources`. So, you should describe some of reason related to PR. Please let me know that I've missed. 

However, If this plugin should supports that the all of files in `web_accessible_resource` stream out, I think that file globs("images/*.png", "template/*")  is required as following document you put it that is reason for a test or we could discuss about that but still not enough to do it.
- [UPDATES] It's resource files, In my opinion, it would better that resource build will be separated. It might be not frequent and coupled to application code hardly so we can build both or individuals.

About content script, It's already tested in https://github.com/ragingwind/chrome-manifest/blob/master/test/test.js#L38 here and this plugin doesn't support excluding content_scripts yet. so I don't think that do testing for content_script.

**Comment by ramijarrar** [comment]
Not all application code exists in "content_scripts" or "background", so for example we can use `tabs.executeScript` to run some code in the browser context after a particular event (these are only listed in "web_accessible_resources")

I do see what you mean about file globs, I wrote this change quickly and did not consider the implications of globs. I guess we would need full support for globs before this would make sense. In my particular use case, this was not an issue since files are filtered by extension before being processed.

**Comment by ramijarrar** [comment]
To describe my specific use case: I am using the yeoman chrome extension generator (which I believe you are also a maintainer of) and have scripts & styles which are not being transformed/minified by the 'build' task since they are not listed in "background" or "content_scripts".

**Comment by ragingwind** [comment]
My concerns are
- There is [no meaningful updates](https://github.com/ragingwind/gulp-chrome-manifest/blob/master/index.js#L122) for manifest(content_scripts manipulating will be supported). `manifest.web_accessible_resources` just refer to it. this plugin not just for list-up js/css to transform.
- Building for web_accessible_resources is much more complicated  than just minifying and transforming js/css files. Image optimization or html assets handling should be considered as like webapp build task. It might use gulp-useref.

Use or develop a new task is more properly for this case.

**Comment by ramijarrar** [comment]
Not sure what you mean by the first point. At the moment what I am proposing is to pick up only the js/css from `manifest.web_accessible_resources` - what do you think about that?

**Comment by ragingwind** [comment]
Reason of using this plugin is that manipulate manifest.json not only pickup the files in resource path. As I mentioned, I recommend that make another task for it.

```
gulp.task('res', function() {
  const manifest = require('manifest.json');
  return gulp.src(manifest.web_accessible_resource).
        .pipe(gulpif('*.css', cssmin()))
        .pipe(gulpif('*.js', sourcemaps.init()))
        .pipe(gulpif('*.js', uglify()))
        .pipe(gulpif('*.js', sourcemaps.write()))
        .pipe(gulp.dest('.res'));
});

gulp.task('manifest', function() {
    return gulp.src('fixtures/manifest.json')
        .pipe(manifest({
            buildnumber: true,
            exclude: [
              'key'
            ],
            background: {
                target: 'scripts/background.js',
                exclude: [
                    'scripts/not-exist-test-script1.js',
                    'scripts/willbe-remove-only-for-debug.js',
                    'components/jquery/jquery.min.js',
                ]
            }
        }))
        .pipe(gulpif('*.css', cssmin()))
        .pipe(gulpif('*.js', sourcemaps.init()))
        .pipe(gulpif('*.js', uglify()))
        .pipe(gulpif('*.js', sourcemaps.write()))
        .pipe(gulp.dest('.tmp'));
});

gulp.task('build', [res, manifest]);
```

this tasks will be more useful, clear and expandable to manage another types assets like image

**Comment by ramijarrar** [comment]
Okay - that works.

**Pull request closed without merging**
